package general.hashcode;

/**
 * Hashing is the process of mapping the data to some representative integer value using the concept of hashing algorithms.
 * In Java, a hash code is an integer value that is linked with each object.
 * Hashing finds its data structure implementation in HashTables and HashMaps.
 * hashCode in Java is a function that returns the hashcode value of an object on calling.
 * It returns an integer or a 4 bytes value which is generated by the hashing algorithm.
 */
public class HashCodeExample {
    public static void main(String[] args) {
        String studentName0 = "Antony";
        String studentName1 = "Antony";
        String studentName2 = "Romain";
        if(studentName0.equals(studentName1))
            System.out.println("Equal variable :\n"+studentName0.hashCode()+"\n"+studentName1.hashCode());
        if(!studentName0.equals(studentName2))
            System.out.println("Un-equal variable :\n"+studentName0.hashCode()+"\n"+studentName2.hashCode());
    }
}
